# Generated by Django 4.2.9 on 2024-01-15 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, null=True)),
                ('op1', models.CharField(max_length=100, null=True)),
                ('op2', models.CharField(max_length=100, null=True)),
                ('op3', models.CharField(max_length=100, null=True)),
                ('op4', models.CharField(max_length=100, null=True)),
                ('answer', models.CharField(max_length=100, null=True)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.creator')),
            ],
        ),
    ]
