# Generated by Django 4.2.9 on 2024-01-19 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_quiz_category_question_qcid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answered_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, null=True)),
                ('mark', models.CharField(max_length=100, null=True)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.creator')),
                ('qcid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.quiz_category')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.question')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userreg')),
            ],
        ),
    ]
